MCU = atmega32u2

BOOTLOADER = atmel-dfu

MOUSEKEY_ENABLE = yes

BOOTMAGIC_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
RGBLIGHT_ENABLE = no

LAYOUTS = tkl_ansi

DEFAULT_FOLDER=xelaco/pegasushoof/2015
