#ifndef CONFIG_H
#define CONFIG_H

#define LOCKING_SUPPORT_ENABLE
#define LOCKING_RESYNC_ENABLE

#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLED_NUM 4
#define RGBLIGHT_HUE_STEP 16
#define RGBLIGHT_SAT_STEP 32
#define RGBLIGHT_VAL_STEP 32

#define MIDI_ADVANCED

#define SLIDER_PIN D4

#define TAPPING_TERM 200

#endif
