MCU = atmega32u4

BOOTLOADER = atmel-dfu

BACKLIGHT_ENABLE = yes
RGBLIGHT_ENABLE = yes

EXTRAKEY_ENABLE = no
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
API_SYSEX_ENABLE = no
SLEEP_LED_ENABLE = no

LAYOUTS = ortho_4x12 planck_mit
LAYOUTS_HAS_RGB = no
