BACKLIGHT_ENABLE = yes
RGBLIGHT_ENABLE = yes

EXTRAKEY_ENABLE = no
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
SLEEP_LED_ENABLE = no

LAYOUTS_HAS_RGB = no
AUDIO_SUPPORTED = no
BACKLIGHT_SUPPORTED = no
